FILE(MAKE_DIRECTORY "/home/blackpc/open-source-workspaces/decision_making_robot_examples/devel/share/dm_lizi/graphs" )
FILE(GLOB_RECURSE FOR_DEL /home/blackpc/open-source-workspaces/decision_making_robot_examples/devel/share/dm_lizi/graphs/* )
#message("delete files from /home/blackpc/open-source-workspaces/decision_making_robot_examples/devel/share/dm_lizi/graphs/ : ${FOR_DEL}")
if( FOR_DEL )
	FILE(REMOVE ${FOR_DEL})
endif()
execute_process(COMMAND /home/blackpc/git/robil/ws/devel/lib/decision_making_parser/decision_making_parser -pe -xml -dot -src "/home/blackpc/open-source-workspaces/decision_making_robot_examples/src/dm_lizi" -dst "/home/blackpc/open-source-workspaces/decision_making_robot_examples/devel/share/dm_lizi/graphs" -f "/home/blackpc/open-source-workspaces/decision_making_robot_examples/src/dm_lizi/src/Wandering.cpp:" RESULT_VARIABLE rv)
FILE(GLOB_RECURSE CREATED_FILES RELATIVE /home/blackpc/open-source-workspaces/decision_making_robot_examples/devel/share/dm_lizi/graphs/ /home/blackpc/open-source-workspaces/decision_making_robot_examples/devel/share/dm_lizi/graphs/*.scxml /home/blackpc/open-source-workspaces/decision_making_robot_examples/devel/share/dm_lizi/graphs/*.btxml  /home/blackpc/open-source-workspaces/decision_making_robot_examples/devel/share/dm_lizi/graphs/*.taoxml)
message("   -- Created XML files:")
foreach( f ${CREATED_FILES})
     message("      -- ${f} ")
endforeach()
FILE(GLOB_RECURSE CREATED_FILES_ABS /home/blackpc/open-source-workspaces/decision_making_robot_examples/devel/share/dm_lizi/graphs/*.scxml /home/blackpc/open-source-workspaces/decision_making_robot_examples/devel/share/dm_lizi/graphs/*.btxml /home/blackpc/open-source-workspaces/decision_making_robot_examples/devel/share/dm_lizi/graphs/*.taoxml)
execute_process(COMMAND "python" /home/blackpc/git/robil/ws/devel/lib/decision_making_parser/decision_making_xml_parser.py -i "/home/blackpc/open-source-workspaces/decision_making_robot_examples/src/dm_lizi" "/home/blackpc/open-source-workspaces/decision_making_robot_examples/devel/share/dm_lizi/graphs" "${CREATED_FILES_ABS}" RESULT_VARIABLE rv)
FILE(GLOB_RECURSE CREATED_FILES RELATIVE /home/blackpc/open-source-workspaces/decision_making_robot_examples/devel/share/dm_lizi/graphs/ /home/blackpc/open-source-workspaces/decision_making_robot_examples/devel/share/dm_lizi/graphs/*.dot /home/blackpc/open-source-workspaces/decision_making_robot_examples/devel/share/dm_lizi/graphs/*.xot)
message("   -- Created DOT files:")
foreach( f ${CREATED_FILES})
     message("      -- ${f} ")
endforeach()
FILE(GLOB_RECURSE CREATED_FILES_ABS /home/blackpc/open-source-workspaces/decision_making_robot_examples/devel/share/dm_lizi/graphs/*.dot)
foreach( f ${CREATED_FILES_ABS} )
	execute_process(COMMAND "dot" -Tgif -o${f}.gif  ${f} RESULT_VARIABLE rv)
endforeach()
FILE(GLOB_RECURSE CREATED_FILES RELATIVE /home/blackpc/open-source-workspaces/decision_making_robot_examples/devel/share/dm_lizi/graphs/ /home/blackpc/open-source-workspaces/decision_making_robot_examples/devel/share/dm_lizi/graphs/*.gif)
message("   -- Created GIF files:")
foreach( f ${CREATED_FILES})
     message("      -- ${f} ")
endforeach()
